RustCrypto/password-hashes

- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- pbkdf2/tests/lib.rs
Hi, I have a try to update the dependencies to the new versions but I got to a point here I would need your opinion.
When I compile it with these changes this will be the result.
```
error[E0382]: use of moved value: `salt`
--> pbkdf2\src\lib.rs:41:9
|
40 |         xor(chunk, &salt.code());
|                     ---- value moved here
41 |         salt
|         ^^^^ value used here after move
|
= note: move occurs because `salt` has type `crypto_mac::MacResult<<F as crypto_mac::Mac>::OutputSize>`, which does not implement the `Copy` trait
```
Looks like that code returns a generic array and takes self as exclusive owner. Reading the docs I found this [1], what do you think of using clone_from? But to using I would have to create a new MacResult from an empty GenericArray and use it to …
> *NOT WORKING* Try to upgrade dependencies

- pbkdf2/Cargo.toml
- pbkdf2/src/errors.rs
- pbkdf2/src/lib.rs
- pbkdf2/tests/lib.rs
Ported `pbkdf2_simple` and `pbkdf2_check`, and corresponding tests and docs from [`rust-crypto`](https://github.com/DaGenix/rust-crypto/blob/master/src/pbkdf2.rs).
> Port utility functions for pbkdf2 from rust-crypto

- pbkdf2/src/lib.rs
Currently the XOR function checks if the salt lenght is greater than or equal to itself:
```rust
[inline(always)]
fn xor(res: &mut [u8], salt: &[u8]) {
assert!(salt.len() >= salt.len(), "length mismatch in xor");
for i in 0..res.len() {
res[i] ^= salt[i];
}
}
```
I believe it actually should be checking that it's greater than or equal to `res`. Currently this doesn't show up in tests because the salt value is always passed with an `F::OutputSize` length and `chunk` will always be <= `F::OutputSize`, but I think this should be fixed in case the implementation changes in the future. I've checked the versions available on crates.io(0.1.0, 0.2.0, 0.2.1), too see if they all are implemented in a way that `chunk` will never be greater in length than a salt value passed. I found no problems with …
> Bug in pbkdf2 xor function

- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- scrypt/Cargo.toml
- scrypt/src/lib.rs
- scrypt/src/romix.rs
Updates to `byte-tools = 0.3` and adds `byteorder = 1.2` for endianness conversion.
> Update byte-tools to 0.3 and add byteorder crate

- .travis.yml
- pbkdf2/src/lib.rs
- scrypt/src/errors.rs
- scrypt/src/lib.rs
- scrypt/src/params.rs
Fixing #3. I've also corrected some docs in `pbkdf2` and added a "Recommended values" section to `ScryptParams`. These recommended values have been taken from the [golang scrypt package](https://godoc.org/golang.org/x/crypto/scrypt).
> Add scrypt documentation

- pbkdf2/Cargo.toml
- scrypt/Cargo.toml
Hi, we released version 2 of `subtle` (context: https://github.com/RustCrypto/traits/pull/33#issue-238854180 ).
As far as I can tell, `subtle` is only used for `ConstantTimeEq`, which is only used internally, so this dependency upgrade will not be a semver breaking change.
> Use subtle v2

- Cargo.toml
- pbkdf2/src/lib.rs
- scrypt/Cargo.toml
Implements the API changes from:
https://github.com/RustCrypto/traits/pull/161
The `hmac` crate now uses `update` and `finalize` nomenclature ala the Initialize-Update-Finalize (IUF) interface naming scheme.
> Rename `*result*` to `finalize`

- scrypt/src/params.rs
This makes it easier to use by moving it to its own function.
> Easy creation of recommended ScryptParam

- pbkdf2/Cargo.toml
- pbkdf2/src/simple.rs
> pbkdf2: bump `rand` dependency to v0.7

- scrypt/Cargo.toml
- scrypt/src/errors.rs
- scrypt/src/lib.rs
- scrypt/src/params.rs
- scrypt/src/simple.rs
Makes `std` optional, relying on `alloc` for heap-allocated data structures and `core` for everything else.
> scrypt: `std` feature

- scrypt/src/lib.rs
The current documentation has an unneeded `fn main() {}` in the *Usage* section. This commit removes the line; alternatively, the code example could be wrapped in `main`.
> Remove superflous main() in documentation

- Cargo.lock
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- Bump `crypto-mac` dependency to v0.9 ([#44])
[#44]: https://github.com/RustCrypto/password-hashing/pull/44
- Bump `pbkdf2` dependency to v0.5 ([#45])
[#45]: https://github.com/RustCrypto/password-hashing/pull/45
> Release pbkdf2 v0.5.0 + scrypt v0.4.0

- scrypt/src/lib.rs
This PR changes the example in `scrypt` to generate the `params` using `ScryptParams::recommended()`, per discussion in #49.
Confirmed it's working by running doc tests.
```bash
❯ cargo test --doc
Finished test [unoptimized + debuginfo] target(s) in 0.02s
Doc-tests scrypt
running 1 test
test src/lib.rs -  (line 13) ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
> docs (scrypt): use ScryptParams::recommended() in usage example

- Cargo.lock
- scrypt/Cargo.toml
- scrypt/src/romix.rs
Closes #29.
Using the `salsa20` crate allows us to focus on a single place for things like SIMD optimizations (#16).
> scrypt: use `salsa20` crate to implement Salsa20/8

- Cargo.lock
- bcrypt-pbkdf/CHANGELOG.md
- bcrypt-pbkdf/Cargo.toml
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
Cuts the following new releases which include an upgrade to `crypto-mac` v0.10 (#58):
- `bcrypt-pbkdf` v0.4.0
- `pbkdf2` v0.6.0
- `scrypt` v0.5.0
> Release new versions

- .github/workflows/sha-crypt.yml
- Cargo.lock
- sha-crypt/Cargo.toml
- sha-crypt/README.md
- sha-crypt/src/lib.rs
Adds a GitHub Actions workflow for `sha-crypt` as well as the standard README.md boilerplate we use for other crates in this repo.
> sha-crypt: CI config and documentation boilerplate

- sha-crypt/Cargo.toml
- sha-crypt/src/lib.rs
Adds `doc_cfg` for https://docs.rs to document functions gated on the `include_simple` feature.
> sha-crypt: add doc_cfg

- Cargo.lock
- sha-crypt/Cargo.toml
- sha-crypt/src/lib.rs
Consistent with the other crates in this repo
> sha-crypt: use `subtle` crate

- .github/workflows/sha-crypt.yml
- sha-crypt/Cargo.toml
- sha-crypt/src/b64.rs
- sha-crypt/src/errors.rs
- sha-crypt/src/lib.rs
- sha-crypt/src/params.rs
Adds basic support for disabling a `std` feature.
Presently still requires liballoc.
Also adds CI for builds on some no_std platforms.
> sha-crypt: `std` feature (i.e. preliminary `no_std` support)

- .github/workflows/bcrypt-pbkdf.yml
- .github/workflows/pbkdf2.yml
- .github/workflows/scrypt.yml
- .github/workflows/workspace.yml
- Cargo.lock
- Cargo.toml
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/README.md
- pbkdf2/Cargo.toml
- pbkdf2/README.md
- pbkdf2/src/hasher.rs
- pbkdf2/src/lib.rs
- pbkdf2/src/simple.rs
- pbkdf2/tests/hasher.rs
- scrypt/Cargo.toml
- scrypt/README.md
Implements the PHC string format for hashes, currently gated under the `include_simple` cargo feature.
Specifics of how the format is encoded/decoded are modeled off of the implementation of PHC hashes for PBKDF2 implemented by Auth0.
See this thread for more information:
https://community.auth0.com/t/bulk-user-import-custom-password-hash-issue/47408/5
> pbkdf2: add PHC hash support using `password-hash` crate

- .github/workflows/argon2.yml
- Cargo.lock
- argon2/Cargo.toml
- argon2/src/error.rs
- argon2/src/instance.rs
- argon2/src/lib.rs
- argon2/tests/phc_strings.rs
- argon2/tests/test_vectors.rs
- pbkdf2/src/hasher.rs
- pbkdf2/tests/hasher.rs
Uses the `password-hash` crate to implement PHC string format support
> argon2: PHC string format support

- Cargo.lock
- argon2/src/lib.rs
- pbkdf2/src/hasher.rs
Flattens module structure for errors
> argon2+pbkdf2: update `password-hash` dependency

- .github/workflows/pbkdf2.yml
- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- pbkdf2/src/simple.rs
- pbkdf2/tests/simple.rs
- scrypt/Cargo.toml
- scrypt/src/errors.rs
- scrypt/src/lib.rs
- scrypt/src/simple.rs
- scrypt/tests/mod.rs
- sha-crypt/Cargo.toml
- sha-crypt/src/b64.rs
- sha-crypt/src/defs.rs
- sha-crypt/src/errors.rs
- sha-crypt/src/lib.rs
- sha-crypt/tests/mod.rs
This name seems more idiomatic in regard to Rust crate features
> Rename "include_simple" features to "simple"

- Cargo.lock
- pbkdf2/Cargo.toml
There are several vestigial dependencies from the old `include_simple` feature which are now no-longer needed as the `password-hash` crate wraps up the same concerns.
> pbkdf2: remove unused dependencies

- Cargo.lock
- bcrypt-pbkdf/Cargo.toml
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- scrypt/Cargo.toml
- PHC hash format support using `password-hash` crate ([#82])
- Rename `include_simple` features to `simple` ([#99])
- Legacy `simple` API ([#98])
[#82]: https://github.com/RustCrypto/password-hashing/pull/82
[#98]: https://github.com/RustCrypto/password-hashing/pull/98
[#99]: https://github.com/RustCrypto/password-hashing/pull/99
> pbkdf2 v0.7.0

- pbkdf2/Cargo.toml
- pbkdf2/src/simple.rs
They are trivial to remove as `password-hash` was written with the intent of "heapless" support, so might as well remove them.
> pbkdf2: remove `alloc` dependencies for `simple` feature

- Cargo.lock
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- `alloc` dependencies for `simple` feature ([#107])
[#107]: https://github.com/RustCrypto/password-hashing/pull/107
> pbkdf2 v0.7.1

- .github/workflows/scrypt.yml
- Cargo.lock
- pbkdf2/src/simple.rs
- scrypt/Cargo.toml
- scrypt/src/errors.rs
- scrypt/src/lib.rs
- scrypt/src/params.rs
- scrypt/src/simple.rs
- scrypt/tests/mod.rs
Implements the PHC string format for hashes, gated under the `simple` cargo feature.
Specifics of how the format is encoded/decoded are modeled off of how passlib implements PHC scrypt hashes:
https://passlib.readthedocs.io/en/stable/lib/passlib.hash.scrypt.html
> scrypt: add PHC hash support using `password-hash` crate

- scrypt/Cargo.toml
- scrypt/benches/lib.rs
- scrypt/src/lib.rs
- scrypt/src/params.rs
- scrypt/src/simple.rs
- scrypt/tests/mod.rs
This follows RFC 356 naming conventions:
https://rust-lang.github.io/rfcs/0356-no-module-prefixes.html
> scrypt: rename ScryptParams => Params

- .github/workflows/sha-crypt.yml
- sha-crypt/README.md
- sha-crypt/src/lib.rs
Slightly closer to heapless support
> sha-crypt: remove `Vec` from public API

- Cargo.lock
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- PHC hash support using `password-hash` crate ([#111])
- Rename `include_simple` features to `simple` ([#99])
- Rename `ScryptParams` => `Params` ([#112])
[#99]: https://github.com/RustCrypto/password-hashing/pull/99
[#111]: https://github.com/RustCrypto/password-hashing/pull/111
[#112]: https://github.com/RustCrypto/password-hashing/pull/112
> scrypt v0.6.0

- Cargo.lock
- sha-crypt/CHANGELOG.md
- sha-crypt/Cargo.toml
- sha-crypt/src/lib.rs
- Bump `rand` dependency to v0.8 ([#86])
- Rename `include_simple` feature to `simple` ([#99])
- Remove `Vec` from public API ([#113]) 
- MSRV 1.47+ ([#113])
[#86]: https://github.com/RustCrypto/password-hashing/pull/86
[#99]: https://github.com/RustCrypto/password-hashing/pull/99
[#113]: https://github.com/RustCrypto/password-hashing/pull/113
> sha-crypt v0.2.0

- Cargo.lock
- bcrypt-pbkdf/CHANGELOG.md
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/src/lib.rs
- Bump `pbkdf2` dependency to v0.7 ([#102])
[#102]: https://github.com/RustCrypto/password-hashing/pull/102
> bcrypt-pbkdf v0.5.0

- Cargo.lock
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- Bump `base64ct` dependency to v0.2 ([#119])
[#119]: https://github.com/RustCrypto/password-hashing/pull/119
> pbkdf2 v0.7.2

- Cargo.lock
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- Bump `base64ct` dependency to v0.2 ([#119])
[#119]: https://github.com/RustCrypto/password-hashing/pull/119
> scrypt v0.6.1

- Cargo.lock
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- `Params` accessor methods ([#123])
[#123]: https://github.com/RustCrypto/password-hashing/pull/123
> scrypt v0.6.2

- argon2/Cargo.toml
Enables the `rand_core` feature of `password-hash`.
Enabled-by-default.
> argon2: add `rand` feature

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/src/lib.rs
- `rand` feature; enabled-by-default ([#126])
[#126]: https://github.com/RustCrypto/password-hashes/pull/126
> argon2 v0.1.1

- argon2/CHANGELOG.md
- argon2/Cargo.toml
- rustdoc typo ([#128])
[#128]: https://github.com/RustCrypto/password-hashes/pull/128
> argon2 v0.1.2

- Cargo.lock
- pbkdf2/Cargo.toml
This makes the `SaltString::generate` function available.
> pbkdf2: enable `rand_core` feature of `password-hash`

- .github/workflows/pbkdf2.yml
- Cargo.lock
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- Enable `rand_core` feature of `password-hash` ([#130])
[#130]: https://github.com/RustCrypto/password-hashing/pull/130
> pbkdf2 v0.7.3

- argon2/src/lib.rs
Adds some additional advance checks that Argon2 parameters are within range, and returns errors in the event they are not.
This prevents a panic caused by what was previously an `unimplemented!` call when converting error types.
The occurrence of the panic in the first place speaks to overall deficiencies in the `password-hash` crate's error handling strategy.
It's further complicated by the awkwardness of the `password_hash::Output::init_with` API.
The code in this commit has TODOs for addressing the above, but it'd be good to open issues upstream on the `password-hash` crate about these problems, and ideally update the TODOs in the code with references to the issues.
cc @izik1
> argon2: avoid salt-length related panic (closes #134)

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- Salt-length related panic ([#135])
[#135]: https://github.com/RustCrypto/password-hashes/pull/135
> argon2 v0.1.3

- scrypt/Cargo.toml
This makes the `SaltString::generate` function available.
- Related: #130
- Closes: #138
> scrypt: enable `rand_core` feature of `password-hash`

- Cargo.lock
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- Enable `rand_core` feature of `password-hash` ([#139])
[#139]: https://github.com/RustCrypto/password-hashing/pull/139
> scrypt v0.6.3

- argon2/Cargo.toml
- pbkdf2/Cargo.toml
- scrypt/Cargo.toml
Enables `password-hash/std` feature, allowing crates like argon2 to throw error up from password-hash.
This is helpful in situations where you want to bubble up the error:
```sh
error[E0277]: the trait bound `HashError: StdError` is not satisfied
--> auth/src/models.rs:104:47
|
104 |     let parsed_hash = PasswordHash::new(&hash)?;
|                                               ^ the trait `StdError` is not implemented for `HashError`
|
= note: required because of the requirements on the impl of `From<HashError>` for `anyhow::Error`
= note: required by `std::convert::From::from`
```
> Enable password-hash/std feature

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- `std` feature ([#141])
[#141]: https://github.com/RustCrypto/password-hashes/pull/141
> argon2 v0.1.4

- Cargo.lock
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- Bump `base64ct` dependency to v1.0 ([#144])
[#144]: https://github.com/RustCrypto/password-hashing/pull/144
> pbkdf2 v0.7.4

- Cargo.lock
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- Bump `base64ct` dependency to v1.0 ([#144])
[#144]: https://github.com/RustCrypto/password-hashing/pull/144
> scrypt v0.6.4

- pbkdf2/Cargo.toml
- scrypt/Cargo.toml
We've had some reports of compile errors due to an unexpected SemVer-breaking change (#147, #150).
This pins the `password-hash` version to one that's guaranteed to be compatible with the current releases.
Closes #150.
> pbkdf2+scrypt: pin to `password-hash` v0.1.2

- Cargo.lock
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- Pin `password-hash` to v0.1.2 or newer ([#151])
[#151]: https://github.com/RustCrypto/password-hashing/pull/151
> pbkdf2 v0.7.5

- Cargo.lock
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- Pin `password-hash` to v0.1.2 or newer ([#151])
[#151]: https://github.com/RustCrypto/password-hashing/pull/151
> scrypt v0.6.5

- Cargo.lock
- argon2/Cargo.toml
- argon2/src/instance.rs
- argon2/src/lib.rs
Adds parallel processing for lanes 
Closes #103 
The parallelism is gated behind the feature `parallel`  
When the feature is activated, the `#![forbid(unsafe_code)]` gets downgraded to `#![deny(unsafe_code)]` due to unsafe usage ([here](https://github.com/smallglitch/password-hashes/blob/f06f51d04bae051dc9ae809f016a3c85b82dac3a/argon2/src/instance.rs#L127-L135))  
The `#![no_std]` flag is being disabled as well
> argon2: Add parallel lane processing

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- Parallel lane processing using `rayon` ([#149])
[#149]: https://github.com/RustCrypto/password-hashes/pull/149
> argon2 v0.1.5

- argon2/src/lib.rs
Eventually it'd be nice to have a safe parallel implementation as well:
https://github.com/RustCrypto/password-hashes/issues/154
> argon2: forbid unsafe code outside parallel implementation

- argon2/src/instance.rs
- argon2/src/lib.rs
- argon2/src/memory.rs
Also makes `Instance` accept `Memory` as a parameter.
This is in preparation for moving slice handling to `Memory`.
> argon2: move `Memory` to its own module

- argon2/src/instance.rs
- argon2/src/lib.rs
- argon2/src/memory.rs
Begins the work of moving calculations about the memory buffer to the `Memory` type.
> argon2: move segment length calculation to `Memory` type

- argon2/src/block.rs
- argon2/src/instance.rs
- argon2/src/lib.rs
Also deprecates the previous `argon2::BLOCK_SIZE` constant.
> argon2: use Block::SIZE constant

- Cargo.lock
- Cargo.toml
- argon2/Cargo.toml
- argon2/src/lib.rs
- argon2/src/params.rs
- argon2/src/version.rs
- bcrypt-pbkdf/tests/test_vectors.rs
- pbkdf2/Cargo.toml
- pbkdf2/src/simple.rs
- pbkdf2/tests/lib.rs
- pbkdf2/tests/simple.rs
- scrypt/Cargo.toml
- scrypt/src/params.rs
- scrypt/src/simple.rs
- sha-crypt/tests/mod.rs
This is a set of changes which corresponds to the proposed breaking changes to the `password-hash` crate:
https://github.com/RustCrypto/traits/pull/615
> password-hash: v0.2 breaking changes

- Cargo.lock
- Cargo.toml
- argon2/Cargo.toml
- pbkdf2/Cargo.toml
- scrypt/Cargo.toml
Release notes: https://github.com/RustCrypto/traits/pull/624
> Bump `password-hash` crate dependency to v0.2

- Cargo.lock
- bcrypt-pbkdf/Cargo.toml
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- scrypt/Cargo.toml
- Bump `password-hash` crate dependency to v0.2 ([#164])
- Bump `hmac` and `crypto-mac` crate deps to v0.11 ([#165])
[#164]: https://github.com/RustCrypto/password-hashing/pull/164
[#165]: https://github.com/RustCrypto/password-hashing/pull/165
> pbkdf2 v0.8.0

- Cargo.lock
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- Bump `password-hash` crate dependency to v0.2 ([#164])
- Bump `hmac` and `crypto-mac` crate deps to v0.11 ([#165])
- Bump `salsa20` crate dependency to v0.8 ([#166])
- Bump `pbkdf2` crate dependency to v0.8 ([#167])
[#164]: https://github.com/RustCrypto/password-hashing/pull/164
[#165]: https://github.com/RustCrypto/password-hashing/pull/165
[#166]: https://github.com/RustCrypto/password-hashing/pull/166
[#167]: https://github.com/RustCrypto/password-hashing/pull/167
> scrypt v0.7.0

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/src/lib.rs
- Forbid unsafe code outside parallel implementation ([#157])
- Bump `password-hash` crate dependency to v0.2 ([#164])
- `argon2::BLOCK_SIZE` constant ([#161])
[#157]: https://github.com/RustCrypto/password-hashes/pull/157
[#161]: https://github.com/RustCrypto/password-hashes/pull/161
[#164]: https://github.com/RustCrypto/password-hashes/pull/164
> argon2 v0.2.0

- Cargo.lock
- bcrypt-pbkdf/CHANGELOG.md
- bcrypt-pbkdf/Cargo.toml
- Bump `crypto-mac` dependency to v0.11 ([#165])
- Bump `pbkdf2` to v0.8 ([#167])
[#165]: https://github.com/RustCrypto/password-hashing/pull/165
[#167]: https://github.com/RustCrypto/password-hashing/pull/167
> bcrypt-pbkdf v0.6.0

- argon2/src/lib.rs
The latest release is 0.2 and I'm not sure that Cargo resolves to that from 0.1.
I might be wrong though so please ignore if so :)
> Bump argon version number in docs

- Cargo.lock
- bcrypt-pbkdf/CHANGELOG.md
- bcrypt-pbkdf/Cargo.toml
- Bump `blowfish` dependency to v0.8 ([#171])
[#171]: https://github.com/RustCrypto/password-hashing/pull/171
> bcrypt-pbkdf v0.6.1

- argon2/src/error.rs
- argon2/src/lib.rs
Adds a proper conversion between argon2::Error and password_hash::Error and uses it when hashing the password.
> argon2: error handling improvements

- argon2/src/error.rs
- argon2/src/lib.rs
Now that error handling has been improved in `password-hash` v0.2, these are no longer needed as the errors will be properly handled in the `hash_password_into` function.
> argon2: eliminate redundant checks added in #135

- argon2/src/algorithm.rs
- argon2/src/lib.rs
- argon2/src/params.rs
Closes #179.
This commit makes the `Params` struct always available regardless of enabled crate features, adding on functionality when the `password-hash` feature is enabled.
Per the added TODOs in this commit, it really seems like in the next breaking release, `Argon2::new` should accept `Params` as an argument rather than duplicating all of the individual parameter fields and passing them in as arguments. After that, they can be validated and stored within the `Argon2` struct itself. But that would be a breaking change, so for now they're stored piecemeal.
Additionally, this commit now ensures enough context is available in the `Argon2` struct in order to implement `hash_password_simple` that uses the configured params rather than the defaults, which addresses the aforementioned issue.
> argon2: make `Params` always available; fix `hash_password_simple`

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- `Params` always available; no longer feature-gated on `password-hash` ([#182])
- Configured params are used with `hash_password_simple` ([#182])
[#182]: https://github.com/RustCrypto/password-hashes/pull/182
> argon2 v0.2.1

- .github/workflows/workspace.yml
- argon2/Cargo.toml
- bcrypt-pbkdf/Cargo.toml
- sha-crypt/src/lib.rs
Locks `zeroize` to a supported MSRV range `>=1, <1.4`, since neither of these crates require functionality specific to 1.3.
This allows more possible version combinations, preventing needless incompatibilities.
> Relax `zeroize` requirements

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/src/lib.rs
- Relax `zeroize` requirements to `>=1, <1.4` ([#195])
[#195]: https://github.com/RustCrypto/password-hashes/pull/195
> argon2 v0.2.3

- argon2/src/error.rs
- argon2/src/lib.rs
> argon2: move `extern crate std` directive

- argon2/src/lib.rs
- argon2/src/params.rs
Support for initializing the algorithm from its parameters.
The `Params` struct has `pub` fields and therefore doesn't validate its parameters, so we need a fallible conversion here.
An alternative would be to have `Params` always validate its parameters, removing the `pub` fields and replacing them with reader methods. This would allow an infallible `From` conversion instead.
This is noted as a TODO in params.rs.
> argon2: impl TryFrom<Params> for Argon2

- argon2/src/algorithm.rs
- argon2/src/error.rs
- argon2/src/instance.rs
- argon2/src/lib.rs
- argon2/src/params.rs
- argon2/src/version.rs
Adds an alias for `Result<T, argon2::Error>` and uses it throughout the implementation to simplify the specification of results.
> argon2: add `Result` type alias

- argon2/src/lib.rs
- argon2/src/params.rs
Adds a builder type which simplifies constructing `Params`.
> argon2: add `ParamsBuilder`

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/src/lib.rs
- Impl `std::error::Error` for `argon2::Error` ([#200])
- Impl `TryFrom<Params>` for `Argon2` ([#202])
- `Result` type alias ([#203])
- `ParamsBuilder` ([#204])
[#200]: https://github.com/RustCrypto/password-hashes/pull/200
[#202]: https://github.com/RustCrypto/password-hashes/pull/202
[#203]: https://github.com/RustCrypto/password-hashes/pull/203
[#204]: https://github.com/RustCrypto/password-hashes/pull/204
> argon2 v0.2.4

- Cargo.lock
- pbkdf2/Cargo.toml
- pbkdf2/src/simple.rs
- pbkdf2/tests/simple.rs
- scrypt/Cargo.toml
- scrypt/src/simple.rs
- scrypt/tests/mod.rs
The Modular Crypt Format (MCF) is a legacy format, and the implementations provided in the `pbkdf2` and `scrypt` crates implement a bespoke RustCrypto-specific format.
Since that format has been introduced, support has been added to both crates for the newer PHC String Format:
https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md
See the "Usage" rustdoc for the respective crates for information on how to use the PHC string format.
Previous releases of these respective crates support converting from the MCF hash format to the PHC format using `McfHasher::upgrade_mcf_hash`:
https://docs.rs/password-hash/0.3.0/password_hash/trait.McfHasher.html#tymethod.upgrade_mcf_hash
Before upgrading these crates to the new release which removes MCF hash support, please use the older …
> Remove `McfHasher` impls for `pbkdf2` and `scrypt` crates

- .github/workflows/argon2.yml
- .github/workflows/bcrypt-pbkdf.yml
- .github/workflows/pbkdf2.yml
- .github/workflows/scrypt.yml
- .github/workflows/sha-crypt.yml
- .github/workflows/workspace.yml
- Cargo.lock
- Cargo.toml
- argon2/Cargo.toml
- argon2/README.md
- bcrypt-pbkdf/Cargo.toml
- pbkdf2/README.md
- scrypt/README.md
- sha-crypt/Cargo.toml
- sha-crypt/README.md
This enables performing a much more exhaustive set of tests for `no_std` targets, which as of #215 all crates in this repo are fully capable.
> Use `resolver = "2"`; MSRV 1.51+

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/src/lib.rs
- `alloc` feature ([#215])
- `Params` now supports `keyid` and `data` fields ([#216])
- `Argon2::new` now has explicit `version` and `params` ([#213])
- Factored apart `Argon2::new` and `Argon2::new_with_secret`, making the
former infallible ([#213])
- `Params` struct is now opaque with field accessors, and ensured to
always represent a valid set of parameters ([#213])
- Removed `version` parameter from `hash_password_into`, using the one
supplied to `Argon2::new` ([#213])
- Bump `password-hash` to v0.3 ([#217], [RustCrypto/traits#724])
- `Params` no longer has a `version` field ([#211])
[#211]: https://github.com/RustCrypto/password-hashes/pull/211
[#213]: https://github.com/RustCrypto/password-hashes/pull/213
[#215]: …
> argon2 v0.3.0

- Cargo.lock
- bcrypt-pbkdf/CHANGELOG.md
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/src/lib.rs
- Relax `zeroize` requirements ([#195])
[#195]: https://github.com/RustCrypto/password-hashes/pull/195
[#220]: https://github.com/RustCrypto/password-hashes/pull/220
> bcrypt-pbkdf v0.7.0

- Cargo.lock
- argon2/Cargo.toml
- bcrypt-pbkdf/Cargo.toml
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- scrypt/Cargo.toml
- sha-crypt/Cargo.toml
- GOST test vectors ([#191])
- Bump `password-hash` to v0.3 ([#217], [RustCrypto/traits#724])
- `McfHasher` impl on `Pbkdf2` ([#219])
[#191]: https://github.com/RustCrypto/password-hashing/pull/191
[#217]: https://github.com/RustCrypto/password-hashing/pull/217
[#219]: https://github.com/RustCrypto/password-hashing/pull/219
[#220]: https://github.com/RustCrypto/password-hashing/pull/220
[RustCrypto/traits#724]: https://github.com/RustCrypto/traits/pull/724
> pbkdf2 v0.9.0

- Cargo.lock
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- scrypt/src/lib.rs
- Bump `password-hash` to v0.3 ([#217])
- Bump `pbkdf2` dependency to v0.9 ([#233])
- `McfHasher` impls for `Scrypt` ([#219])
[#217]: https://github.com/RustCrypto/password-hashing/pull/217
[#219]: https://github.com/RustCrypto/password-hashing/pull/219
[#220]: https://github.com/RustCrypto/password-hashing/pull/220
[#233]: https://github.com/RustCrypto/password-hashing/pull/233
> scrypt v0.8.0

- Cargo.lock
- sha-crypt/CHANGELOG.md
- sha-crypt/Cargo.toml
- sha-crypt/src/defs.rs
- sha-crypt/src/errors.rs
- sha-crypt/src/lib.rs
- sha-crypt/src/params.rs
[#220]: https://github.com/RustCrypto/password-hashes/pull/220
> sha-crypt v0.3.0

- Cargo.lock
- bcrypt-pbkdf/CHANGELOG.md
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/src/lib.rs
- Bump `pbkdf2` dependency to v0.9 ([#223])
[#223]: https://github.com/RustCrypto/password-hashes/pull/223
> bcrypt-pbkdf v0.7.1

- sha-crypt/src/b64.rs
- sha-crypt/src/errors.rs
- sha-crypt/src/lib.rs
- sha-crypt/tests/lib.rs
Changes the B64 decoder to return a `Result`, returning an error if the input is invalid instead of panicking.
Fixes #240
> sha-crypt: handle B64 decoding errors

- Cargo.lock
- sha-crypt/CHANGELOG.md
- sha-crypt/Cargo.toml
- sha-crypt/src/lib.rs
- Handle B64 decoding errors ([#242])
[#242]: https://github.com/RustCrypto/password-hashes/pull/242
> sha-crypt v0.3.1

- argon2/src/lib.rs
The docs for version "0.3.1" recommend version "0.2" in the docs.
This fixes it.
> Fixed version in docs

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/LICENSE-MIT
- argon2/src/lib.rs
- Make `Params::block_count()` public ([#258])
[#258]: https://github.com/RustCrypto/password-hashes/pull/258
> argon2 v0.3.3

- .github/workflows/argon2.yml
- .github/workflows/balloon-hash.yml
- .github/workflows/bcrypt-pbkdf.yml
- .github/workflows/pbkdf2.yml
- .github/workflows/scrypt.yml
- .github/workflows/sha-crypt.yml
- Cargo.lock
- README.md
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/src/lib.rs
- balloon-hash/CHANGELOG.md
- balloon-hash/Cargo.toml
- balloon-hash/src/lib.rs
- bcrypt-pbkdf/CHANGELOG.md
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/README.md
- bcrypt-pbkdf/src/lib.rs
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- scrypt/README.md
- scrypt/src/lib.rs
- scrypt/src/params.rs
- scrypt/src/romix.rs
- scrypt/src/simple.rs
Also bumps MSRV and edition to 1.56 and 2021 respectively for `bcrypt-pbkdf` and `scrypt`.
> Test and fix min versions build

- pbkdf2/src/lib.rs
The example presented in documentation comment can't be compiled with version 0.7, so I'd like to update it.
> docs: update corresponding version in doc

- .github/workflows/argon2.yml
- .github/workflows/balloon-hash.yml
- .github/workflows/bcrypt-pbkdf.yml
- .github/workflows/pbkdf2.yml
- .github/workflows/scrypt.yml
- .github/workflows/workspace.yml
- Cargo.lock
- argon2/Cargo.toml
- argon2/README.md
- argon2/src/algorithm.rs
- argon2/src/lib.rs
- balloon-hash/Cargo.toml
- balloon-hash/README.md
- balloon-hash/src/algorithm.rs
- balloon-hash/src/lib.rs
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/README.md
- pbkdf2/Cargo.toml
- pbkdf2/README.md
- pbkdf2/src/lib.rs
- pbkdf2/src/simple.rs
- scrypt/Cargo.toml
- scrypt/README.md
- scrypt/src/lib.rs
- scrypt/src/simple.rs
Release notes: https://github.com/RustCrypto/traits/pull/961
> Bump `password-hash` dependency to v0.4; MSRV 1.57

- .github/workflows/sha-crypt.yml
- README.md
- argon2/Cargo.toml
- argon2/README.md
- argon2/src/algorithm.rs
- argon2/src/block.rs
- argon2/src/lib.rs
- argon2/src/params.rs
- argon2/src/version.rs
- balloon-hash/Cargo.toml
- balloon-hash/src/algorithm.rs
- balloon-hash/src/lib.rs
- balloon-hash/src/params.rs
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/src/lib.rs
- pbkdf2/Cargo.toml
- pbkdf2/src/simple.rs
- pbkdf2/tests/simple.rs
- scrypt/Cargo.toml
- sha-crypt/Cargo.toml
- sha-crypt/README.md
- sha-crypt/src/lib.rs
Bumps all crates which weren't previously upgraded to the 2021 edition to the 2021 edition.
All crates were already MSRV 1.57 as of #283, except `sha-crypt`.
This commit bumps all crates to the 2021 edition, including `sha-crypt`.
> 2021 edition upgrades

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/src/block.rs
- argon2/src/lib.rs
- Bump `password-hash` dependency to v0.4; MSRV 1.57 ([#283])
- 2021 edition upgrade ([#284])
[#283]: https://github.com/RustCrypto/password-hashes/pull/283
[#284]: https://github.com/RustCrypto/password-hashes/pull/284
> argon2 v0.4.0

- Cargo.lock
- balloon-hash/CHANGELOG.md
- balloon-hash/Cargo.toml
- balloon-hash/src/lib.rs
- Bump `password-hash` dependency to v0.4; MSRV 1.57 ([#283])
- 2021 edition upgrade ([#284])
[#283]: https://github.com/RustCrypto/password-hashes/pull/283
[#284]: https://github.com/RustCrypto/password-hashes/pull/284
> balloon-hash v0.2.0

- Cargo.lock
- balloon-hash/Cargo.toml
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/src/lib.rs
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- scrypt/Cargo.toml
- scrypt/src/lib.rs
- Bump `password-hash` dependency to v0.4; MSRV 1.57 ([#283])
- 2021 edition upgrade ([#284])
[#283]: https://github.com/RustCrypto/password-hashes/pull/283
[#284]: https://github.com/RustCrypto/password-hashes/pull/284
> pbkdf2 v0.11.0

- Cargo.lock
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- scrypt/src/lib.rs
- Bump `password-hash` dependency to v0.4; MSRV 1.57 ([#283])
- Bump `pbkdf2` dependency to v0.11 ([#291])
[#283]: https://github.com/RustCrypto/password-hashes/pull/283
[#291]: https://github.com/RustCrypto/password-hashes/pull/291
> scrypt v0.10.0

- Cargo.lock
- sha-crypt/CHANGELOG.md
- sha-crypt/Cargo.toml
- sha-crypt/src/lib.rs
- 2021 edition upgrade; MSRV 1.56 ([#284])
[#284]: https://github.com/RustCrypto/password-hashes/pull/284
> sha-crypt v0.4.0

- argon2/src/lib.rs
A small follow-up to https://github.com/RustCrypto/password-hashes/pull/306.
The proposition here is to be able to use `RECOMMENDED_SALT_LEN` without having to pull in another dependency. Is that alright?
Sorry for being so brusk, I thought instead of asking with an issue I can simply ask with a PR.
> Remove crate feature from `argon2::RECOMMENDED_SALT_LEN`

- argon2/src/lib.rs
The example in the docs for version 0.4 uses version 0.3 of the crate. This updates it.
> argon2: update version in docs

- balloon-hash/src/balloon.rs
- balloon-hash/src/error.rs
- balloon-hash/src/lib.rs
~~Depends on #312.~~
Fixes #310.
> Implement `Balloon::hash_into`

- Cargo.lock
- argon2/src/lib.rs
- balloon-hash/tests/balloon.rs
This version added a check that encoded Base64 is canonical, i.e. that the decoded value will round-trip back to the encoded value.
Some of the test vectors did not have this property and have been fixed.
> Bump `base64ct` to v1.5.1

- scrypt/src/simple.rs
I ended up on the [`Scrypt` struct's page] while trying to figure out how to use the crate and it wasn't obvious what the associated function to actually hash a password was. This commit adds a link to the crate-level usage example to (hopefully) prevent folks from getting lost like I did.
[`Scrypt` struct's page]: https://docs.rs/scrypt/0.10.0/scrypt/struct.Scrypt.html
> doc: Add a link to scrypt's usage example

- sha-crypt/src/lib.rs
- sha-crypt/tests/lib.rs
1) in produce_byte_seq, the fill_from slice will always be 64 bytes in
length, due to the SHA512 algorithm digest supplying these bytes
2) produce_byte_seq() was attempting to index the fill_from slice beyond
the 64 bytes when a password > 64 bytes in length was being used
signed-off-by: Michael Mullin <masmullin@gmail.com>
Addresses: https://github.com/RustCrypto/password-hashes/issues/327
> sha-crypt: enable passwords longer than 64 bytes in length

- scrypt/src/params.rs
- scrypt/tests/mod.rs
I've faced with an issue when i need dynamically specify the output length of scrypt function. With current state of your crate it's not possible because in `Params::new` there is a statically used output hash length (RECOMMENDED_LEN = 64 bytes), so i don't understand why it's "recommended" if there is no choice
> ability to use custom output key length for scrypt

- Cargo.lock
- scrypt/Cargo.toml
- scrypt/benches/lib.rs
- scrypt/src/params.rs
Followup to #255.
This fixes a clippy error and bumps the version to v0.11.0-pre as #255 contained a breaking change.
> scrypt: fix clippy; bump to v0.11.0-pre

- Cargo.lock
- argon2/Cargo.toml
- argon2/src/block.rs
- argon2/src/lib.rs
- Bump version to `0.5.0-pre` ([#247](https://github.com/RustCrypto/password-hashes/pull/333) contained breaking changes)
- Use pointer casts to convert `Block` integer array to byte array
- Rename `permutate!` to `permute!` (former isn't in OED, latter is)
cc @Pjottos
> argon2: followups to #247

- argon2/src/blake2b_long.rs
- argon2/src/lib.rs
- argon2/src/params.rs
Expands the set of clippy lints applied to include ones intended to eliminate panics.
Replaces `usize::try_from(n: u32).unwrap()` usages with `as u32` to avoid panics, avoiding possible truncation by adding a `compile_error!` if the `target_pointer_width` isn't 32 or 64-bit.
> argon2: add clippy lints to avoid panics

- .github/workflows/password-auth.yml
- Cargo.lock
- Cargo.toml
- argon2/Cargo.toml
- password-auth/CHANGELOG.md
- password-auth/Cargo.toml
- password-auth/LICENSE-APACHE
- password-auth/LICENSE-MIT
- password-auth/README.md
- password-auth/src/lib.rs
Adds a high-level password hashing crate which is a facade over other crates in this repo, namely the `argon2`, `pbkdf2`, and `scrypt` crates.
The crate has been designed with an extremely simple API with only `generate_hash` and `verify_password` functions.
The API surface deliberately avoids exposing anything from other crates, allowing for rapid iteration towards a 1.0 release even if the crates it's built on are not yet 1.0.
> password-auth: initial crate

- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/src/errors.rs
- bcrypt-pbkdf/src/lib.rs
- bcrypt-pbkdf/tests/test_vectors.rs
I'm using `bcrypt-pbkdf` in an embedded context without a global allocator. To support this, I added a new function `bcrypt_pbkdf_with_memory`, which takes in an additional memory buffer argument (similar to some of the other crates in this repo with an optional alloc feature).
> `bcrypt-pbkdf` without `alloc`

- argon2/Cargo.toml
zeroize is not used on Vec or String types for argon2, so removing the default alloc feature allows the zeroize feature to be enabled in argon2 for no-std targets.
> Disable default feature (i.e. alloc) of zeroize in argon2

- pbkdf2/src/lib.rs
- pbkdf2/src/simple.rs
For RustCrypto members
Thank you for developing a awesome crate!
I have a question.
Why do the other crates maintained by this repository have published Ident values, but not in `pbkdf2`?
Looking at the code, it seems that there is an intention to publish it, but it is not available because there is no `use` declaration.
If you just forgot to publish it, I would appreciate it if you could merge this PR and make it available.
> pbkdf2: make public PBKDF2 Ident values

- argon2/src/params.rs
Adopts the recommended settings from:
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
> Use Argon2id with a minimum configuration of 19 MiB of memory, an
> iteration count of 2, and 1 degree of parallelism.
> argon2: adopt OWASP recommendations

- argon2/src/params.rs
- scrypt/src/params.rs
Makes the defaults easier to inspect from the rustdoc
> scrypt: add inherent constants for `Params` recommendations

- scrypt/src/params.rs
Adopts the recommended settings from:
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
> use scrypt with a minimum CPU/memory cost parameter of (2^17),
> a minimum block size of 8 (1024 bytes), and a parallelization
> parameter of 1.
> scrypt: adopt OWASP recommendations

- pbkdf2/src/lib.rs
- pbkdf2/src/simple.rs
Adopts the recommended settings from:
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
> use PBKDF2 with a work factor of 600,000 or more and set with an
> internal hash function of HMAC-SHA-256.
> pbkdf2: adopt OWASP recommendations

- Cargo.lock
- sha-crypt/Cargo.toml
It was pinned to preserve MSRV, but that creates huge compatibility headaches for downstream users
> sha-crypt: relax `subtle` dependency

- .github/workflows/argon2.yml
- .github/workflows/password-auth.yml
- Cargo.lock
- README.md
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/README.md
- password-auth/Cargo.toml
- password-auth/README.md
- Key derivation usage example ([#366])
- Inherent constants for `Params` recommendations ([#387])
- Merge `Argon2` and `Instance` structs ([#247])
- Refactor `ParamsBuilder` to make it more ergonomic ([#247])
- Bump `password-hash` dependency to v0.5 ([#383])
- Adopt OWASP recommended default `Params` ([#386])
- MSRV 1.65 ([#391])
- Erroneous docs for `m_cost` and `Block` ([#247])
- Allow `zeroize` in heapless environments (i.e. without `alloc`) ([#374])
- `Memory` struct ([#247])
- Unsound `parallel` feature - see [#380] ([#247])
[#247]: https://github.com/RustCrypto/password-hashes/pull/247
[#366]: https://github.com/RustCrypto/password-hashes/pull/366
[#374]: https://github.com/RustCrypto/password-hashes/pull/374
[#380]: https://github.com/RustCrypto/password-hashes/pull/380
[#383]: …
> argon2 v0.5.0

- Cargo.lock
- balloon-hash/CHANGELOG.md
- balloon-hash/Cargo.toml
- Bump `crypto-bigint` to v0.5; MSRV 1.65 ([#381])
- Bump `password-hash` to v0.5 ([#383])
[#381]: https://github.com/RustCrypto/password-hashes/pull/381
[#383]: https://github.com/RustCrypto/password-hashes/pull/383
> balloon-hash v0.4.0

- Cargo.lock
- bcrypt-pbkdf/Cargo.toml
- password-auth/Cargo.toml
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- scrypt/Cargo.toml
- Add new wrapper functions: `pbkdf2_array`, `pbkdf2_hmac`, and
`pbkdf2_hmac_array`. `pbkdf2` and `pbkdf2_array` now return
`Result<(), InvalidLength>` instead of unwrapping it internally. ([#337])
- Use `sha1` dependency directly ([#363])
- Make `Ident` values inherent constants of `Algorithm` ([#375])
- Bump `password-hash` to v0.5 ([#383])
- Adopt OWASP recommended default `Params` ([#389])
- `simple` feature is no longer enabled by default ([#336])
[#336]: https://github.com/RustCrypto/password-hashes/pull/336
[#337]: https://github.com/RustCrypto/password-hashes/pull/337
[#363]: https://github.com/RustCrypto/password-hashes/pull/363
[#375]: https://github.com/RustCrypto/password-hashes/pull/375
[#383]: https://github.com/RustCrypto/password-hashes/pull/383
[#389]: …
> pbkdf2 v0.12.0

- Cargo.lock
- bcrypt-pbkdf/CHANGELOG.md
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/README.md
- bcrypt-pbkdf/src/lib.rs
- Support for `alloc`-free usage ([#372])
- Bump `pbkdf2` dependency to v0.12; MSRV 1.60 ([#393])
[#372]: https://github.com/RustCrypto/password-hashes/pull/372
[#393]: https://github.com/RustCrypto/password-hashes/pull/393
> bcrypt-pbkdf v0.10.0

- Cargo.lock
- password-auth/Cargo.toml
- scrypt/CHANGELOG.md
- scrypt/Cargo.toml
- Ability to use custom output key length ([#255])
- Inherent constants for `Params` recommendations ([#387])
- Bump `password-hash` to v0.5; MSRV 1.60 ([#383])
- Adopt OWASP recommendations ([#388])
- Bump `pbkdf2` to v0.12 ([#393])
[#255]: https://github.com/RustCrypto/password-hashes/pull/255
[#383]: https://github.com/RustCrypto/password-hashes/pull/383
[#387]: https://github.com/RustCrypto/password-hashes/pull/387
[#388]: https://github.com/RustCrypto/password-hashes/pull/388
[#393]: https://github.com/RustCrypto/password-hashes/pull/393
> scrypt v0.11.0

- sha-crypt/CHANGELOG.md
- sha-crypt/Cargo.toml
- `sha256_crypt` ([#350])
- Use `base64ct` for Base64 encoding ([#350])
- MSRV 1.60 ([#377])
- Relax `subtle` dependency version requirements ([#390])
- Support passwords longer than 64-bytes in length ([#328])
[#328]: https://github.com/RustCrypto/password-hashes/pull/328
[#350]: https://github.com/RustCrypto/password-hashes/pull/350
[#377]: https://github.com/RustCrypto/password-hashes/pull/377
[#390]: https://github.com/RustCrypto/password-hashes/pull/390
> sha-crypt v0.5.0

- Cargo.lock
- pbkdf2/src/lib.rs
Re-exports the crate when the `hmac` feature is enabled
> pbkdf2: re-export `hmac`

- Cargo.lock
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- Re-export `hmac` ([#397])
[#397]: https://github.com/RustCrypto/password-hashes/pull/397
> pbkdf2 v0.12.1

- argon2/src/params.rs
Shortcut for creating an `Argon2` context from `ParamsBuilder`
> argon2: add `ParamsBuilder::context`

- .github/workflows/argon2.yml
- .github/workflows/balloon-hash.yml
- .github/workflows/bcrypt-pbkdf.yml
- .github/workflows/password-auth.yml
- .github/workflows/pbkdf2.yml
- .github/workflows/readme.yml
- .github/workflows/scrypt.yml
- .github/workflows/sha-crypt.yml
- .github/workflows/workspace.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/password-hashes/actions/runs/4416508641: 
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct …
> Replace unmaintained actions-rs/* actions in CI workflows

- argon2/src/algorithm.rs
Previously `Algorithm::as_str` used no lifetime specifier on the returned `as_str`, so the returned value inherited the lifetime of `&self`.
But the returned value are static value and could use the lifetime `'static` instead.
> Annotate `Algorithm::as_str` returning static str

- argon2/src/block.rs
For `#![no_std]` environments, adding the const initializer makes it possible to write
```rust
static mut ARGON2_MEMBLOCK: [argon2::Block; MEM_BLOCK_COUNT] = [argon2::Block::new(); MEM_BLOCK_COUNT];
```
Previously, without a const initializer for `argon2::Block`, doing the same would require code like the following:
```rust
static mut MEM_BLOCKS: [MaybeUninit<argon2::Block>; MEM_BLOCK_COUNT] = unsafe {MaybeUninit::uninit().assume_init()};
// Initialize blocks when they are actually used
```
Unfortunately, the compiler is not able to optimize the initialization properly, resulting in an extra 1KB of space wasted on the stack, which becomes an issue in memory-constrained embedded systems. The following program is an illustration of this:
```rust
#![no_std]
use core::mem::MaybeUninit;
use …
```
> Add const initializer to argon2::Block

- password-auth/README.md
- password-auth/src/errors.rs
- password-auth/src/lib.rs
Adds a method for interrogating whether a given password hash is using the recommended algorithm and parameters.
This can be used by password hash upgrade systems to determine whether a particular hash should be upgraded/recomputed.
It additionally adds a `ParseError` type which wraps `password_hash::Error`. This is only used by `is_hash_obsolete` for now but it might be good for future versions to use this error type to capture parse errors in `verify_password`.
However, that would be a breaking change, which is avoided for now.
Closes #426
> password-auth: add `is_hash_obsolete`

- Cargo.lock
- password-auth/Cargo.toml
- password-auth/src/errors.rs
- password-auth/src/lib.rs
`VerifyError` was previously the return type for the `verify_password` function which has two distinct error cases:
- Password hash failed to parse
- Password is invalid
This commit replaces `VerifyError` with an `Error` enum which captures both cases.
It leverages the `ParseError` type which was added in #428.
> password-auth: replace `VerifyError` with `Error` enum

- Cargo.lock
- password-auth/CHANGELOG.md
- password-auth/Cargo.toml
- `is_hash_obsolete` ([#428])
- Replace `VerifyError` with `Error` enum ([#429])
[#428]: https://github.com/RustCrypto/password-hashes/pull/428
[#429]: https://github.com/RustCrypto/password-hashes/pull/429
> password-auth v0.2.0

- password-auth/src/lib.rs
The "Returns" section was incorrectly documented
> password-auth: fix `is_hash_obsolete` docs

- Cargo.lock
- password-auth/Cargo.toml
- password-auth/src/errors.rs
- password-auth/src/lib.rs
The name better captures the intent: errors relating to `verify_password`.
Using the same name should ease upgrades as well.
> password-auth: rename `Error` (back) to `VerifyError`

- password-auth/src/errors.rs
Derives these traits for the following types:
- `ParseError`
- `VerifyError`
> password-auth: derive `Eq`/`PartialEq` on `*Error`

- Cargo.lock
- password-auth/CHANGELOG.md
- password-auth/Cargo.toml
- password-auth/README.md
- Derive `Eq`/`PartialEq` on `*Error` ([#433])
- Rename `Error` (back) to `VerifyError` ([#432])
[#432]: https://github.com/RustCrypto/password-hashes/pull/432
[#433]: https://github.com/RustCrypto/password-hashes/pull/433
> password-auth v0.3.0

- scrypt/src/params.rs
When updating the parameters in a previous PR (#388) this documentation was missed.
> scrypt: Update docs for recommended log_n parameter

- argon2/src/params.rs
Allows for accessing default parameters in const contexts
> argon2: add `Params::DEFAULT` constant

- Cargo.lock
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- Use `RECOMMENDED_ROUNDS` in `Default` impl for `Params` ([#442])
[#442]: https://github.com/RustCrypto/password-hashes/pull/442
> pbkdf2 v0.12.2

- Cargo.lock
- argon2/Cargo.toml
- argon2/src/block.rs
- argon2/src/lib.rs
- benches/Cargo.toml
- benches/src/argon2.rs
I've tried my hardest to get this to work, but I think I'm in a little over my head. The most I've managed to do is port the [macros from the optimized reference version](https://github.com/P-H-C/phc-winner-argon2/blob/f57e61e19229e23c4445b85494dbf7c07de721cb/src/blake2/blamka-round-opt.h).
~~My main problem is that I have no idea how these indexes into `state` work:~~
~~https://github.com/P-H-C/phc-winner-argon2/blob/92cd2e1/src/opt.c#L94-L102~~
If someone could give me a hand, I'd be happy to fix/finish this. This is the first time I've ever tried to do stuff with SIMD, so bear with me as I'm still learning.
related to #104
> argon2: optimize with AVX2 SIMD

- argon2/src/block.rs
- argon2/src/lib.rs
This changes `Argon2::compress` to contain all AVX2-related logic, so it doesn't bleed into the `Block` type yet (especially since that lacks any AVX2-specific implementation).
> argon2: fold `compress_avx2` into an inner function

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- Provide `std::error::Error::source` for `argon2::Error` ([#379])
- `ParamsBuilder::context` ([#400])
- Enable `password-hash/alloc` when `alloc` feature is enabled ([#422])
- Impl `Debug` for `Argon2` ([#423])
- `Block::new()` const initializer ([#427])
- `Params::DEFAULT` constant ([#439])
- Initial AVX2 SIMD optimizations ([#440])
[#379]: https://github.com/RustCrypto/password-hashes/pull/379
[#400]: https://github.com/RustCrypto/password-hashes/pull/400
[#422]: https://github.com/RustCrypto/password-hashes/pull/422
[#423]: https://github.com/RustCrypto/password-hashes/pull/423
[#427]: https://github.com/RustCrypto/password-hashes/pull/427
[#439]: https://github.com/RustCrypto/password-hashes/pull/439
[#440]: https://github.com/RustCrypto/password-hashes/pull/440
> argon2 v0.5.1

- argon2/src/algorithm.rs
- argon2/src/lib.rs
- argon2/src/params.rs
- argon2/src/version.rs
This reverts commit 5e3f574c96a3c6aa6ddffdfeb323edb3b400f2d7.
These changes are incompatible with #440, which performs runtime CPU feature detection.
> Revert "argon2: improve `const` compatibility (#438)"

- argon2/src/algorithm.rs
- argon2/src/lib.rs
- argon2/src/params.rs
- argon2/src/version.rs
Redo of #438 after #440.
Rebased original PR, then applied fixes and then sqashed
> argon2: more const-ness

- Cargo.lock
- password-auth/CHANGELOG.md
- password-auth/Cargo.toml
This release is unchanged from v0.3.0.
The goal of this crate is to provide a facade with simple API which does not contain any re-exports from its dependencies, which is why it's possible to cut a v1.0.0 release.
This allows the underlying `argon2`, `pbkdf2`, and `scrypt` crates to be updated without any user-facing changes.
> password-auth v1.0.0

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- Improved `const fn` support ([#450])
- Max params ([#452])
[#450]: https://github.com/RustCrypto/password-hashes/pull/450
[#452]: https://github.com/RustCrypto/password-hashes/pull/452
> argon2 v0.5.2

- argon2/src/params.rs
* The minimum value of `m_cost` is 8 ( 8*`MIN_OUTPUT_LEN`), not 1.
* The maximum value of `p_cost` is (2^24)-1, not 255.
These are defined in [RFC 9106](https://datatracker.ietf.org/doc/html/rfc9106), and [`MIN_M_COST`](https://docs.rs/argon2/0.5.2/argon2/struct.Params.html#associatedconstant.MIN_M_COST) and [`MAX_P_COST`](https://docs.rs/argon2/0.5.2/argon2/struct.Params.html#associatedconstant.MAX_P_COST) are also like that.
See also: #451, #452
> Argon2: Fix `Params` docs

- argon2/src/params.rs
According to [RFC 9106](https://datatracker.ietf.org/doc/html/rfc9106):
> Memory size m **MUST** be an integer number of kibibytes from 8\*p to
> 2^(32)-1. The actual number of blocks is m', which is m rounded
> down to the nearest multiple of 4\*p.
See also: https://github.com/RustCrypto/password-hashes/pull/458#issuecomment-1706637626
> Argon2: Fix docs about minimum value of `m_cost`

- Cargo.lock
The latest version requires Rust 1.63, which is higher than `pbkdf2`'s MSRV:
https://github.com/RustCrypto/password-hashes/actions/runs/6794257921/job/18470364231?pr=471
```
error: package `rayon-core v1.12.0` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.60.0
Error: Process completed with exit code 101.
```
> Cargo.lock: downgrade `rayon` to 1.7.0

- .github/workflows/argon2.yml
- argon2/src/block.rs
- argon2/src/lib.rs
- argon2/tests/kat.rs
This was broken in #247, which added unsafe pointer casts to access the contents of a block, which only works on little endian targets.
This reverts back to something closer to the previous code, which used `u64::{from_le_bytes, to_le_bytes}` instead.
It also adds cross tests for PPC32 to spot future regressions.
Fixes #481.
> argon2: fix big endian support

- Cargo.lock
- argon2/CHANGELOG.md
- argon2/Cargo.toml
- argon2/LICENSE-MIT
- Documentation ([#458], [#459])
- Big endian support  ([#482])
[#458]: https://github.com/RustCrypto/password-hashes/pull/458
[#459]: https://github.com/RustCrypto/password-hashes/pull/459
[#482]: https://github.com/RustCrypto/password-hashes/pull/482
> argon2 v0.5.3

- .github/workflows/argon2.yml
- .github/workflows/balloon-hash.yml
- .github/workflows/bcrypt-pbkdf.yml
- .github/workflows/password-auth.yml
- .github/workflows/pbkdf2.yml
- .github/workflows/scrypt.yml
- .github/workflows/sha-crypt.yml
- .github/workflows/workspace.yml
- Cargo.lock
- Cargo.toml
- argon2/Cargo.toml
- balloon-hash/Cargo.toml
- balloon-hash/src/balloon.rs
- balloon-hash/src/lib.rs
- balloon-hash/tests/balloon.rs
- balloon-hash/tests/balloon_m.rs
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/src/lib.rs
- password-auth/Cargo.toml
- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
- scrypt/Cargo.toml
- sha-crypt/Cargo.toml
Prepare releases of:
- balloon-hash `0.5.0-pre.0`
- bcrypt-pbkdf `0.11.0-pre.0`
- password-auth `1.1.0-pre.0`
- pbkdf2 `0.13.0-pre.0`
- scrypt `0.12.0-pre.0`
- sha-crypt `0.6.0-pre.0`
- argon2 `0.6.0-pre.0`
This brings:
- digest `=0.11.0-pre.8`
- sha1 `=0.11.0-pre.3`
- sha2 `=0.11.0-pre.3`
- hmac `=0.13.0-pre.3`
- blake2 `=0.11.0-pre3`
> Prepare pre.0 prereleases

- .github/workflows/bcrypt-pbkdf.yml
- .github/workflows/scrypt.yml
- .readme/Cargo.toml
- Cargo.lock
- Cargo.toml
- bcrypt-pbkdf/Cargo.toml
- scrypt/Cargo.toml
Depends on:
- https://github.com/RustCrypto/block-ciphers/pull/413
> bcrypt-pbkdf: scrypt: bump cipher to `0.5.0-pre.4`

- scrypt/src/params.rs
This allows for PartialEq structs that contain an scrypt Params to also be PartialEq.
> Add PartialEq to scrypt::Params

- sha-crypt/src/lib.rs
- sha-crypt/src/params.rs
- sha-crypt/tests/lib.rs
> sha-crypt: Change parameter type and make hashing infallible

- scrypt/src/params.rs
This allows `scrypt::Params::recommended` to be used in a const context, just like `argon2::Params::DEFAULT`.
> Make methods of `scrypt::Params` to `const fn`

- Cargo.lock
- Cargo.toml
- argon2/Cargo.toml
- argon2/tests/kat.rs
- balloon-hash/Cargo.toml
- balloon-hash/src/lib.rs
- bcrypt-pbkdf/Cargo.toml
- bcrypt-pbkdf/src/lib.rs
- pbkdf2/Cargo.toml
- scrypt/Cargo.toml
- sha-crypt/Cargo.toml
Also fixes `hybrid-array` deprecations.
Updates the following:
- `blake2` v0.11.0-pre.4
- `blowfish` v0.10.0-pre.1
- `cipher` v0.5.0-pre.6
- `crypto-bigint` v0.6.0-rc.2
- `digest` v0.11.0-pre.9
- `hmac` v0.13.0-pre.4
- `hybrid-array` v0.2.0-rc.9
- `salsa20` v0.11.0-pre.1
- `sha1` v0.11.0-pre.4
- `sha2` v0.11.0-pre.4
- `streebog` v0.11.0-pre.4
> Bump dependencies to latest prereleases

- Cargo.lock
- argon2/Cargo.toml
- balloon-hash/Cargo.toml
- bcrypt-pbkdf/Cargo.toml
- password-auth/Cargo.toml
- pbkdf2/Cargo.toml
- scrypt/Cargo.toml
- sha-crypt/Cargo.toml
Cuts the following prereleases:
- `argon2` v0.6.0-pre.1
- `balloon-hash` v0.5.0-pre.1
- `bcrypt-pbkdf` v0.11.0-pre.1
- `password-auth` v1.1.0-pre.1
- `pbkdf2` v0.13.0-pre.1
- `scrypt` v0.12.0-pre.1
- `sha-crypt` v0.6.0-pre.1
> Cut pre.1 prereleases

- argon2/Cargo.toml
- argon2/src/lib.rs
A missing weak feature specifier `?` was causing `password-hash` to always become part of a crate's build tree if someone had specified `default-features = false, features = ["alloc"]` in their `Cargo.toml`.
Due to https://github.com/rust-lang/cargo/issues/10801 `password-hash` will still always appear in the lockfile, but it won't be compiled anymore when a downstream crate has only enabled the `alloc` or `std` features.
> argon2: only enable password-hash dependency if its explicit

- fuzz/fuzz_targets/scrypt.rs
Also change ranges used to generate scrypt parameters to prevent potential timeout issues.
cc @arthurscchan
> fuzz: add upper bound for scrypt's password and salt sizes

- argon2/Cargo.toml
- balloon-hash/Cargo.toml
- bcrypt-pbkdf/Cargo.toml
During a recent code audit on another project, I noticed that the `argon2`, `balloon-hash` and `bcrypt-pbkdf` crates implemented in this code repository do not explicitly declare their `zeroize` feature variants for memory sanitization behavior.
Fix this by adding explicit `Cargo.toml` `[feature]` entries for this `zeroize` flag.
By my current understanding, the relevant optional security hardening functionality which is gated by this feature flag can already be used by other crates today if they opt-in to its use in their `[dependencies]` reference, without requiring this patch because the relevant functionality gets picked up as an "implicit feature". 
However, by not explicitly announcing this optional security feature, some consumers will either miss that it exists, or do not regard …
> Add explicit zeroize features

- argon2/src/lib.rs
> argon2: mention requiring `std` crate feature for `OsRng`

- scrypt/src/params.rs
Currently, the `N` parameter can be obtained by raising 2 to the power of `Params::log_n`.
```rust
// example of raising 2 to the power of `Params::log_n`
let n = 1 << params.log_n();
```
I think it's easier to read to use a method which gets the `N` parameter directly instead of this way.
```rust
let n = params.n();
```
> feat(scrypt): Add `Params::n` method

- .github/workflows/argon2.yml
Helps spot issues with `unsafe` code. See:
https://github.com/RalfJung/cargo-careful
> argon2: test using `cargo careful`

- argon2/src/lib.rs
This patch adds an example of peppering as well as salting a password to the library's documentation home page (right under the existing example of salting). I think this is useful because although the `new_with_secret()` method is public & documented, it's purpose is not clear to the general user.
In fact, it took me a while to [spelunk](https://github.com/RustCrypto/password-hashes/issues/194) [through](https://github.com/RustCrypto/traits/issues/694) the [project](https://github.com/RustCrypto/traits/pull/699) to figure it out.
> Add an example of peppering to the docs.

- argon2/src/block.rs
- argon2/src/error.rs
- argon2/src/lib.rs
> argon2: detect allocation failures in `hash_password_into`

- .readme/Cargo.lock
- Cargo.lock
- argon2/src/error.rs
The variant was added in https://github.com/RustCrypto/traits/pull/1782
> argon2: use `password_hash::Error::OutOfMemory`

- Cargo.lock
- Cargo.toml
- pbkdf2/src/lib.rs
Depends; 
- https://github.com/RustCrypto/password-hashes/pull/593
- https://github.com/RustCrypto/traits/pull/1799 
- https://github.com/RustCrypto/hashes/pull/678
- https://github.com/RustCrypto/MACs/pull/186
> chore(deps): use digest newtypes

- .github/workflows/scrypt.yml
- scrypt/src/params.rs
When scrypt used a dependency with `default-features = false`, the doc compilation will fail because `password_hash::PasswordHasher` will be unavailable (`password-hash` is only pulled `simple` feature is used).
It did not show up in CI, because `password-hash` is also provided as a `dev-dependency` and is available when `cargo test` evaluates the documentation.
Fixup #602
> scrypt: fixup doc compilation

- Cargo.lock
- pbkdf2/Cargo.toml
- pbkdf2/tests/mod.rs
Additionally, adds a test vector for `belt-hash`.
> pbkdf2: use helper macro to simplify tests

- Cargo.lock
- argon2/Cargo.toml
- argon2/src/lib.rs
- argon2/src/memory.rs
- benches/Cargo.toml
- benches/src/argon2.rs
Adds a ~~default-enabled~~ `parallel` feature, with an ~~otherwise~~ optional dependency on `rayon`, and parallelize the filling of blocks using the memory views mentioned above.
Coordinated shared access in the memory blocks is implemented with a `SegmentViewIter` iterator, which implements either `rayon::iter::ParallelIterator` or `core::iter::Iterator` and returns `SegmentView` views into the Argon2 blocks memory that are safe to be used in parallel.
The views alias in the regions that are read-only, but are disjoint in the regions where mutation happens. Effectively, they implement, with a combination of mutable borrowing and runtime checking, the cooperative contract outlined in RFC 9106. This is similar to what was suggested in #380.
To avoid aliasing mutable references into the …
> argon2: add parallelism

- yescrypt/src/common.rs
- yescrypt/src/lib.rs
- yescrypt/src/salsa20.rs
- yescrypt/src/sha256.rs
- `uint8_t` => `u8`
- `uint32_t` => `u32`
- `uint64_t` => `u64`
- `size_t` => `usize`
- `libc::c_char` => `i8`
- `libc::c_int` => `i32`
- `libc::c_uint` => `u32`
- `libc::c_ulong` => `u64`
> yescrypt: replace `u*_t` and `size_t` aliases with Rust types

- yescrypt/src/lib.rs
- yescrypt/tests/kats.rs
Previously errors were being ignored.
This adds an `Error` type and changes `yescrypt_kdf` to return a `Result`
> yescrypt: handle `retval`

- yescrypt/src/lib.rs
- yescrypt/tests/kats.rs
Writes into an output `&mut [u8]` instead.
cc @conradludgate
> yescrypt: remove `Vec` from API

- yescrypt/src/lib.rs
- yescrypt/src/pwxform.rs
- yescrypt/src/smix.rs
Removes an instance of `malloc`, replacing it with `Vec`.
Also replaces the immediate first occurance of passing it as a pointer (to `smix`) with a mutable slice, though it's immediately converted to a pointer after that. More work to be done!
> yescrypt: use `Vec` for `PwxformCtx` storage

- yescrypt/src/lib.rs
- yescrypt/src/smix.rs
Replaces the pointer, but still converts to a pointer later in the function. An incremental improvement.
> yescrypt: make buffer arg to `smix` a slice

- yescrypt/src/lib.rs
- yescrypt/src/pwxform.rs
- yescrypt/src/smix.rs
Notably this is the last usages of `malloc`/`free` in the codebase.
Also adds a lifetime to `PxwformCtx` and changes the constructor argument to be a mutable slice.
It's still pointers internally, but this encapsulates a lot of the unsafety, and allows us to remove `unsafe` from the constructor as it's now (externally) safe to call.
> yescrypt: allocate state as a `Vec`

- yescrypt/src/params.rs
- yescrypt/src/params/encoding.rs
Initial support for encoding parameters for Modular Crypt Format strings.
This adapts the reference C code for encoding params from the `yescrypt_encode_params_r` function. It currently optimizes for closeness to the original C over making the code more idiomatic.
Notably the portions of the function for adding the `$y$` prefix and encoding the salt as Base64 have been removed, as the function is directly impl'd on the `Params` type and only deals with encoding those.
Params are encoded as a sequence of "LEB"-like variable-width integers. In the original source code, encoding of the integers and the encoding of Base64 are somewhat entangled, which is preserved here.
In the future, this can be made into an internal function, called by a fuller implementation of the Modular Crypt Format …
> yescrypt: add `Params::encode`

- .github/workflows/yescrypt.yml
- yescrypt/Cargo.toml
- yescrypt/src/lib.rs
- yescrypt/src/pwxform.rs
- yescrypt/src/salsa20.rs
- yescrypt/src/smix.rs
- yescrypt/src/util.rs
Ideally we could ship a crate with MSRV 1.85 so we have a release that works on stable Debian.
This vendors the code for `[T]::as_chunks_mut` and in the process extracts a `util` module to contain the various shared free functions.
There's still a usage of `get_disjoint_mut` which keeps the MSRV at 1.86 which is a bit less trivial to just vendor like this, which is not addressed for now, but ideally we'd have a temporary replacement for that as well.
cc @conradludgate
> yescrypt: extract `util` module; bring MSRV down to 1.86

- .github/workflows/yescrypt.yml
- yescrypt/Cargo.toml
- yescrypt/README.md
- yescrypt/src/pwxform.rs
This is a nice MSRV to release on because we get both the 2024 edition and Debian stable support.
Includes TODOs to use `get_disjoint_mut` when MSRV is 1.86
> yescrypt: restore MSRV 1.85

- yescrypt/src/encoding.rs
- yescrypt/src/params.rs
Add a decoder for yescrypt params strings, translated from the reference C implementation (namely the `yescrypt_r` function from `yescrypt-common.c`)
> yescrypt: params decoder

- Cargo.lock
- yescrypt/Cargo.toml
- yescrypt/src/flags.rs
- yescrypt/src/lib.rs
- yescrypt/src/params.rs
- yescrypt/src/smix.rs
- yescrypt/tests/kats.rs
Pares the `Flags` type down to the minimum that is actually needed.
Moves flags-related functionality into the `Flags` type (notably computing the "flavor" `u32`) and adds some smoke tests.
> yescrypt: refactor `Flags` to remove `bitflags` dependency

- yescrypt/README.md
- yescrypt/src/flags.rs
- yescrypt/src/params.rs
- yescrypt/src/pwxform.rs
Incorporates portions of the paper into comments/rustdoc
> yescrypt: add link to paper and improve docs

- yescrypt/src/flags.rs
- yescrypt/src/lib.rs
Changes it to an explicit parameter of `yescrypt_kdf_body`
> yescrypt: move prehashing out-of-band from `Flags`

- pbkdf2/src/lib.rs
I believe these bounds were only necessary in the older `hmac` versions.
> `pbkdf2`: remove unnecessary bounds

- Cargo.lock
- pbkdf2/CHANGELOG.md
- pbkdf2/Cargo.toml
- pbkdf2/src/lib.rs
> pbkdf2: remove the `parallel` crate feature

- yescrypt/src/encoding.rs
- yescrypt/src/lib.rs
- yescrypt/src/params.rs
- yescrypt/src/pwxform.rs
- yescrypt/src/smix.rs
Fixes offenses, either by masking to show that truncation is expected, using `TryFrom` and `?` to convert to `Error::Internal` if the conversion fails, or starting with a narrower type and widening instead of trying to go the other direction.
> yescrypt: enable `clippy::cast_possible_truncation`
