Cargo.lock
sha-crypt/CHANGELOG.md
sha-crypt/Cargo.toml

Initial release.
Thanks for the contribution, @awidegreen!

sha-crypt v0.1.0

---

pbkdf2/src/hasher.rs
pbkdf2/src/lib.rs
pbkdf2/tests/hasher.rs

Cleanups in prep for adding `password-hash` support to Argon2

pbkdf2: consistency cleanups

---

Cargo.lock
Cargo.toml
argon2/Cargo.toml
pbkdf2/Cargo.toml

https://docs.rs/password-hash/0.1.0/

Use `password-hash` v0.1 crate release

---

Cargo.lock
argon2/CHANGELOG.md
argon2/Cargo.toml
argon2/src/lib.rs

argon2 v0.1.0

---

README.md

README.md: link to OWASP Password Storage Cheat Sheet

---

argon2/src/lib.rs

Multithreading has been implemented

argon2: remove outdated notes

---

argon2/src/instance.rs

It was not being passed correctly to `Instance`
Closes #234

argon2: fix handling of `p_cost` parameter

---

sha-crypt/tests/lib.rs

sha-crypt: test cleanup

---

argon2/src/params.rs

Make `Params::block_count()` public

---

Cargo.lock
README.md
balloon-hash/CHANGELOG.md
balloon-hash/Cargo.toml
balloon-hash/src/lib.rs

balloon-hash v0.1.0

---

scrypt/CHANGELOG.md
scrypt/src/lib.rs

Fix a few typos

---

Cargo.lock
sha-crypt/Cargo.toml
sha-crypt/src/b64.rs
sha-crypt/src/defs.rs
sha-crypt/src/lib.rs
sha-crypt/src/params.rs
sha-crypt/tests/lib.rs

This uses #349 and and is missing some code dedup.

wp: add sha256_crypt

---

argon2/README.md
balloon-hash/README.md
bcrypt-pbkdf/README.md
password-auth/README.md
pbkdf2/README.md
scrypt/README.md
sha-crypt/README.md

They show both the latest crate release and a total download count

README.md(s): use buildstats.info badges for crate-image

---

Cargo.lock
argon2/Cargo.toml
balloon-hash/Cargo.toml
password-auth/Cargo.toml
pbkdf2/Cargo.toml
scrypt/Cargo.toml

Release notes: https://github.com/RustCrypto/traits/pull/1271

Bump `password-hash` to v0.5

---

argon2/src/params.rs

argon2: improve m_cost documentation

---

password-auth/CHANGELOG.md
password-auth/Cargo.toml

password-auth v0.1.0

---

Cargo.lock
password-auth/CHANGELOG.md
password-auth/Cargo.toml

- Improve documentation ([#419])
[#419]: https://github.com/RustCrypto/password-hashes/pull/419

password-auth v0.1.1

---

.github/workflows/argon2.yml
.github/workflows/balloon-hash.yml
.github/workflows/bcrypt-pbkdf.yml
.github/workflows/password-auth.yml
.github/workflows/pbkdf2.yml
.github/workflows/scrypt.yml
.github/workflows/sha-crypt.yml
.github/workflows/workspace.yml
.github/workflows/yescrypt.yml
Cargo.lock
argon2/Cargo.toml
balloon-hash/Cargo.toml
bcrypt-pbkdf/Cargo.toml
password-auth/Cargo.toml
pbkdf2/Cargo.toml
scrypt/Cargo.toml
sha-crypt/Cargo.toml
sha-crypt/src/lib.rs
yescrypt/Cargo.toml

Bump hybrid-array to 0.2.0-rc.10; bump MSRV to 1.81

---

.github/workflows/workspace.yml
argon2/src/lib.rs
balloon-hash/src/lib.rs
bcrypt-pbkdf/src/lib.rs

Also runs `cargo clippy --fix`

CI: bump clippy to 1.84

---

.github/workflows/fuzz_build.yml

The `if` key was in the wrong place:
Error: every step must define a `uses` or `run` key

CI: fix `fuzz_build` config

---

yescrypt/src/lib.rs

Notes that we relicensed the derived code with permission

yescrypt: update licensing comment

---

yescrypt/src/lib.rs

These operations don't rely on wrapping arithmetic and would actually benefit from checked arithmetic in debug mode for catching bugs
cc @conradludgate

yescrypt: remove `wrapping_*` from `yescrypt_kdf_body`

---

yescrypt/src/lib.rs

Also adds a note about this somewhat strange branch/comment from the reference C implementation:
https://github.com/openwall/yescrypt/blob/087682c/yescrypt-ref.c#L771-L777

yescrypt: factor `yescrypt_kdf_inner` into `yescrypt_kdf`

---

yescrypt/src/lib.rs

The original C code has it write into a buffer which isn't used.
Per the deleted comment this is apparently for demonstrating implementation parity with the optimized implementation, which does some form of preallocation which is unused in the reference implementation.
Additionally this converts `yescrypt_kdf_body` to returning a `Result`.

yescrypt: remove no-op `yescrypt_kdf_body` call

---

yescrypt/src/lib.rs
yescrypt/src/params.rs
yescrypt/src/salsa20.rs

Makes code closer to idiomatic Rust

yescrypt: use snake case names

---

yescrypt/src/pwxform.rs

Has `PwxformCtx::pwxform` take a Rust reference instead of a pointer

pwxform: use a reference argument

---

yescrypt/src/lib.rs
yescrypt/src/pwxform.rs

Carries over more constants and comments from the reference C implementation

yescrypt: more constants and comments
